### ISSUE TITLE
Latest version (1.1.1) provided by npm not available on the repo

### ISSUE THREAD

**Issue by ebourmalo** [feathersjs/feathers-query-filters#1]
Hey Eric,

Could you update the repo of the module with the last version please =)

It took me a couple of minutes to understand why I had differences between the module I got from npm and the current one I could see on the repo ^^

Thanks in advance

**Comment by ekryski** [comment]
Apologies. Looks like I had forgotten to push it up. Just pushed up an update.

**Comment by daffl** [comment]
I added the release scripts in https://github.com/feathersjs/feathers-query-filters/commit/ac13bb87f415f681f8c9ce42ef191263bb1ab9a4. You should just be able to run `npm run release:<major/minor/patch` now fully publish a new version.
